# Generated by Django 5.1.4 on 2024-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='subscription_plans/hover/', verbose_name='Изображение при наведении'),
        ),
    ]
