# Generated by Django 5.1.4 on 2024-12-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscriptionplan_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='active_sub_count',
            field=models.IntegerField(default=0, verbose_name='Количество активных подписок'),
        ),
    ]
