# Generated by Django 5.1.4 on 2024-12-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0002_sponsor_calendar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='month',
        ),
    ]
