# Generated by Django 5.1.4 on 2024-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0003_alter_calendar_unique_together_remove_calendar_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('image', models.ImageField(upload_to='year_calendar_images/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Годовой календарь',
                'verbose_name_plural': 'Годовые календари',
                'unique_together': {('year',)},
            },
        ),
    ]
