# Generated by Django 5.1.4 on 2024-12-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0004_yearcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.TextField(verbose_name='О компании')),
                ('position', models.TextField(verbose_name='Позиция')),
                ('candidate_requirements', models.TextField(verbose_name='Требования к кандидату')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('conditions', models.TextField(verbose_name='Условия')),
                ('contact_info', models.TextField(verbose_name='Контактные данные')),
            ],
        ),
    ]
