# Generated by Django 5.1.4 on 2024-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0005_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активная вакансия'),
        ),
    ]
