# Generated by Django 5.1.4 on 2025-02-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_yearly',
            field=models.BooleanField(default=False, verbose_name='Годовой отчет'),
        ),
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=2025, verbose_name='Год'),
        ),
    ]
