# Generated by Django 5.1.4 on 2025-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0008_report_is_yearly_alter_report_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='Количество студентов')),
                ('donated_money', models.PositiveIntegerField(default=0, verbose_name='Сумма пожертвований (₸)')),
                ('donors_count', models.PositiveIntegerField(default=0, verbose_name='Количество жертвователей')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
