# Generated by Django 4.2.28 on 2026-02-08 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0009_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('kz', 'Казахский'), ('ru', 'Русский')], default='kz', max_length=2, unique=True, verbose_name='Язык')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('mission_title', models.CharField(max_length=255, verbose_name='Заголовок миссии')),
                ('mission_text', models.TextField(verbose_name='Текст миссии')),
                ('goals_title', models.CharField(max_length=255, verbose_name='Заголовок целей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ['locale'],
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=2026, verbose_name='Год'),
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст параграфа')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='trustIn.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Параграф',
                'verbose_name_plural': 'Параграфы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст цели')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='trustIn.about', verbose_name='О нас')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
                'ordering': ['order'],
            },
        ),
    ]
