# Generated by Django 4.2.28 on 2026-02-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trustIn', '0010_about_alter_report_year_aboutparagraph_aboutgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('kz', 'Казахский'), ('ru', 'Русский')], default='kz', max_length=2, verbose_name='Язык')),
                ('name', models.CharField(max_length=255, verbose_name='Имя основателя')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('kz', 'Казахский'), ('ru', 'Русский')], default='kz', max_length=2, unique=True, verbose_name='Язык')),
                ('team_title', models.CharField(max_length=255, verbose_name='Заголовок команды')),
                ('founders_title', models.CharField(max_length=255, verbose_name='Заголовок основателей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
                'ordering': ['locale'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('kz', 'Казахский'), ('ru', 'Русский')], default='kz', max_length=2, verbose_name='Язык')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('role', models.CharField(max_length=255, verbose_name='Должность/Роль')),
                ('year', models.CharField(help_text="Например: Есік БИЛ '06", max_length=100, verbose_name='Год выпуска')),
                ('contact', models.CharField(help_text='Телефон', max_length=50, verbose_name='Контактная информация')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_images/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Члены команды',
                'ordering': ['order', 'name'],
            },
        ),
    ]
